### ISSUE TITLE
Cant join servers(i Am trying to Join my own Cracked/Offline Server)

### ISSUE THREAD

**Issue by ghost** [l1ttleO/PrismLauncher-elyby#1]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 6.3

### Version of Qt

6.4.2

### Description of bug

Whenever i try to join Any cracked server it gives "Invalid signature for profile public key. Try restarting your game.".
Log from aternos:
https://mclo.gs/EX7mnNH
(captainvedu is friend in game. "**.**.**.**:62777" is me)

### Steps to reproduce

Open mc in elyby mode and join any cracked server

### Suspected cause

not getting a public key from elyby

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by lemonzest79** [comment]
To run a server that accepts ely.by login download this
https://github.com/yushijinhun/authlib-injector/releases

then start the server with:
java -javaagent:authlib-injector-1.2.2.jar=ely.by -jar server.jar
Edit as necessary for your config

Keep it as a online server not offline, and join with your ely.by account and it should let you in, this is how I run my personal server for myself and friends. I have ran both vanilla and modded servers with this.

**Comment by Octol1ttle** [comment]
^^^ + you must set `enforce-secure-profile` to `false` in `server.properties`
