### ISSUE TITLE
Prism Launcher Updated to release 8.2

### ISSUE THREAD

**Issue by lemonzest79** [l1ttleO/PrismLauncher-elyby#12]
### Role

I Play Modded Minecraft

### Suggestion

Upgrade to latest upstream release of Prism Launcher

### Benefit

So its updated

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

https://github.com/PrismLauncher/PrismLauncher/releases/tag/8.1

**Comment by Octol1ttle** [comment]
![image](https://github.com/Octol1ttle/ElyPrismLauncher/assets/61277953/209f9f63-b969-4d00-95c4-0b992e95fb45)
famous last words

**Comment by lemonzest79** [comment]
They just bumped to 8.2 cos they forgot to raise the minor version number

**Comment by Octol1ttle** [comment]
https://github.com/Octol1ttle/ElyPrismLauncher/releases/tag/8.2
