### ISSUE TITLE
Prism Launcher 8.3 Released

### ISSUE THREAD

**Issue by lemonzest79** [l1ttleO/PrismLauncher-elyby#14]
### Role

I Play Modded Minecraft

### Suggestion

Updated to the latest upstream

### Benefit

Newest version

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

https://github.com/PrismLauncher/PrismLauncher/releases/tag/8.3

Has now been released, thanks

**Comment by Octol1ttle** [comment]
https://github.com/Octol1ttle/ElyPrismLauncher/releases/tag/8.3

**Comment by lemonzest79** [comment]
Thanks :)
