### ISSUE TITLE
Forge Doesnt work on modern versions

### ISSUE THREAD

**Issue by SuckyBuckyYT** [l1ttleO/PrismLauncher-elyby#18]
### Operating System

Windows

### Version of Prism Launcher

Prism Launcher 8.3

### Version of Qt

Qt 6.6.3

### Description of bug

any modern forge does not work on prism launcher it says error this one
![image](https://github.com/Octol1ttle/ElyPrismLauncher/assets/97747818/9b2cffb7-b084-42df-8ea8-41fdb9b7bbe8)
has been happening to me for a while used sklauncher as temporary but prismlauncher rules so wanted to know if there was a fix

### Steps to reproduce

do not know what is steps to reduce 

### Suspected cause

not using an authentic minecraft account

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Octol1ttle** [comment]
Upgrade the Java version used by the instance/launcher

**Comment by SuckyBuckyYT** [comment]
same error with java 21 and took that screenshot java 17
