### ISSUE TITLE
Upstream update

### ISSUE THREAD

**Issue by lemonzest79** [l1ttleO/PrismLauncher-elyby#19]
### Role

I play modded minecraft

### Suggestion

Update to the latest upstream please

### Benefit

so the improvements are included

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

https://github.com/PrismLauncher/PrismLauncher/releases/tag/8.4 Usual Upstream update, thanks

**Comment by lemonzest79** [comment]
Hi, sorry, I hate to push, but wondering if there is any timeframe on this? thank you

**Comment by Octol1ttle** [comment]
Due to ongoing personal difficulties, it will take a bit more time. Currently I don't have access to my computer, I hope to get back to it by the end of ~~this~~ next week, but I can't promise anything

**Comment by lemonzest79** [comment]
Ok thank you, sorry to hear about your personal difficulties, I wish you all the best.

**Comment by Octol1ttle** [comment]
Apologies for the late update.

https://github.com/Octol1ttle/ElyPrismLauncher/releases/tag/8.4
