### ISSUE TITLE
Version 7.2 fixed the bypass

### ISSUE THREAD

**Issue by Minepool9** [l1ttleO/PrismLauncher-elyby#2]
### Operating System

Windows

### Version of Prism Launcher

Prsim launcher 7.2

### Version of Qt

Qt 5.15.10

### Description of bug

So trying to login with ely.by now results in a "Mojang user authentication failed."

### Steps to reproduce

1 download version 7.2
2 try to login to ely.by
3 fail

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Octol1ttle** [comment]
I could not replicate your issue. Can you please provide your log file at `%appdata%\PrismLauncher\logs\PrismLauncher-0.log`

**Comment by lemonzest79** [comment]
I logged in fine to both my Ely.by accounts (Which even have 2FA enabled, FYI enter as password:token) and they both worked fine and I can play on my own Ely.by enabled servers.

**Comment by Octol1ttle** [comment]
Closing due to no response from OP
