### ISSUE TITLE
i can't download modpacks anymore :( 

### ISSUE THREAD

**Issue by NotVoid404** [l1ttleO/PrismLauncher-elyby#22]
### Version of Prism Launcher

prism launcher 8.3

### Version of Qt

Qt version 6.6.3

### Description of bug

Error while creating new instance:Could not rename the overrides folder:overrides

### Steps to reproduce

just trying to download a modpack you know the steps already

### Suspected cause

so this happened just today it was working fine yesterday, I don't know why 

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by NotVoid404** [comment]
i use windows 10

**Comment by NotVoid404** [comment]
prism 8,4 doesn't work for me i can't open it I mean

**Comment by Octol1ttle** [comment]
Duplicate of PrismLauncher/PrismLauncher#1629
