### ISSUE TITLE
Expanded filter for modinth

### ISSUE THREAD

**Issue by whoiamwhy** [l1ttleO/PrismLauncher-elyby#23]
### Role

I use Prism Launcher to create modpacks

### Suggestion

Add a expanded filter for modrinth

### Benefit

It can be more comfortable

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

### You may use the editor below to elaborate further.

Please add a filter to search for mods as done in one of the forks: https://github.com/Diegiwg/PrismLauncher-Cracked/releases/tag/v8.4.1
![image](https://github.com/user-attachments/assets/08cebeb1-0477-4f81-9de5-19f44f06619a)
![image](https://github.com/user-attachments/assets/5316dd2d-0d50-4bde-88d8-06c0ee980202)

**Comment by Octol1ttle** [comment]
It is out of scope for this fork to contain changes not related to usages of Ely.by accounts. Such issues should be submitted to the upstream repository.
