### ISSUE TITLE
GIFs as icons

### ISSUE THREAD

**Issue by NotVoid404** [l1ttleO/PrismLauncher-elyby#24]
### Role

better customization

### Suggestion

i want to use GIFs as icons

### Benefit

some launchers like forge have it

### This suggestion is unique

- [X] I have searched the issue tracker and did not find an issue describing my suggestion, especially not one that has been rejected.

**Comment by Octol1ttle** [comment]
Please submit issues unrelated to Ely functionality to the upstream repository: https://github.com/PrismLauncher/PrismLauncher/issues
