### ISSUE TITLE
Where did the aur package ElyPrismLauncher go?

### ISSUE THREAD

**Issue by pashtetusss777** [l1ttleO/PrismLauncher-elyby#27]
### Operating System

Linux

### Version of Prism Launcher

Prism Launcher 8.4

### Version of Qt

Qt 5

### Description of bug

I can't find the launcher package on aur.archlinux.org
![изображение](https://github.com/user-attachments/assets/a0d14880-f101-4bc8-84c1-1602290a2f26)

### Steps to reproduce

- [ ] Not available at aur.archlinux.org

### Suspected cause

Possibly deleted

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by mctaylors** [comment]
ElyPrismLauncher had no packages (officially) on the AUR. But thanks for the info, I'll see what I can do about it.

**Comment by mctaylors** [comment]
@Octol1ttle

**Comment by Octol1ttle** [comment]
The AUR moderators *still* can't decide whether or not they want to keep software that "bypasses DRM". Unfortunately, some rather lifeless people keep submitting deleting requests for such software (including EPL). The same story happened to Legacy Launcher's package, where it was kept, then deleted, then reinstated, then deleted again.

https://lists.archlinux.org/archives/list/aur-requests@lists.archlinux.org/thread/ZBEUUEL57Y2YQNTFP4U2ZANDATFU5DFK/#ZBEUUEL57Y2YQNTFP4U2ZANDATFU5DFK

https://lists.archlinux.org/archives/list/aur-requests@lists.archlinux.org/thread/C4DPGESONCREOBEGGNRKR7XARK32UPXA/#C4DPGESONCREOBEGGNRKR7XARK32UPXA

If you have any further complaints, please forward them to the AUR moderators. Although they are so disorganised you will probably hear 402 completely contradictory opinions from them.

I can't do anything about this.
Thanks for your understanding.
