### ISSUE TITLE
ElyPrismLauncher Ely.by system not working

### ISSUE THREAD

**Issue by dsijdshaij** [l1ttleO/PrismLauncher-elyby#28]
### Version of Prism Launcher

Prism Launcher 8.5

### Version of Qt

Qt 6.6.3

### Description of bug

Ely by system not working 

### Steps to reproduce

Sign in Ely by

### Suspected cause

I login in my Ely.By account in this launcher and it haves default skin in game, not mine

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

**Comment by Octol1ttle** [comment]
1) PrismLauncher 8.5 doesn't exist?
2) You haven't provided any logs, which are crucial to diagnosing this issue. Provide both launcher logs and game logs.

**Comment by dsijdshaij** [comment]
> 1. PrismLauncher 8.5 doesn't exist?
> 2. You haven't provided any logs, which are crucial to diagnosing this issue. Provide both launcher logs and game logs.

sorry 8.4
also i meant this dont work only in multiplayer
logs
down

**Comment by dsijdshaij** [comment]
[PrismLauncher-4.log](https://github.com/user-attachments/files/17650195/PrismLauncher-4.log)

**Comment by dsijdshaij** [comment]
also, when someone join my world LAN they dont have skin even if they have premium

**Comment by Octol1ttle** [comment]
The issues you are encountering are related to `authlib-injector` (the current method EPL uses to add Ely skins patch). They will be fixed in the future once I switch to Ely Authlib (I can't control when that happens due to external factors)

**Comment by dsijdshaij** [comment]
> h to Ely Authlib (I can't control

when is future
