### ISSUE TITLE
failed to upload skin

### ISSUE THREAD

**Issue by Vibee0** [l1ttleO/PrismLauncher-elyby#7]
### Version of Prism Launcher

Prisma Launcher 8.0

### Version of Qt

Qt 6.6.0

### Description of bug

When I try to upload a skin an error occurs: failed to upload skin.

### Steps to reproduce

ㅤㅤㅤㅤㅤ
ㅤㅤㅤㅤㅤㅤ

### This issue is unique

- [X] I have searched the issue tracker and did not find an issue describing my bug.

### Logs

```
  5264.428 W | QWindowsWindow::setGeometry: Unable to set geometry 480x118+460+381 (frame: 496x157+452+350) on QWidgetWindow/"ProgressDialogWindow" on "L192WS ". Resulting geometry: 480x174+460+381 (frame: 496x213+452+350) margins: 8, 31, 8, 8 minimum size: 480x118 MINMAXINFO(maxSize=POINT(x=0, y=0), maxpos=POINT(x=0, y=0), maxtrack=POINT(x=0, y=0), mintrack=POINT(x=496, y=157)))
  5264.692 C | Network error:  QNetworkReply::AuthenticationRequiredError
  5264.698 W | "Error transferring https://api.minecraftservices.com/minecraft/profile/skins - server replied: "
```

**Comment by Octol1ttle** [comment]
Ely.by does not support uploading skins outside the website. The buttons for skin management will be disabled in the next release.
